# Copyright 2018-2024 Institute of Computer Science of the Czech Academy of
# Sciences, Prague, Czech Republic. Authors: Martin Bures, Jaroslav Resler.
#
# This file is part of PALM-GeM.
#
# PALM-GeM is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# PALM-GeM is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# PALM-GeM. If not, see <https://www.gnu.org/licenses/>.

# input schema and table names
input_schema: 'inputs_prague'

# default domain and case values and domain parameters
domain:
    name: 'case_name'
    scenario: 'scenario_00'
    parent_domain_schema: ''
    dx: 10.0
    dy: 10.0
    dz: 10.0
    nx: 128
    ny: 128
    cent_x: 459180
    cent_y: 5547800

default_height:
    0: 6    # [m]
    1: 6    # [m] Residential, < 1950	33
    2: 6    # [m] Residential, 1950 - 2000	33
    3: 6    # [m] Residential, > 2000	33
    4: 12   # [m] Office, < 1950	33
    5: 12   # [m] Office, 1950 - 2000	33
    6: 12   # [m] Office, > 2000	33

# case table names
tables:
    grid:                   'grid'
    dem:                    'dem'
    buildings_height:       'buildings'   # copied DEM from INPUTS
    buildings_grid:         'buildings_grid' # for top 2d and 3d, gridded table
    landcover:              'landcover'
    walls:                  'walls'
    roofs:                  'roofs'
    buildings_offset:       'buildings_offset'
    aspect:                 'buildings_aspect_deg'
    slope:                  'buildings_slope_deg'
    slanted_wall:           'slanted_wall'
    slanted_roof:           'slanted_roof'
    slanted_terr_wall:      'slanted_terr_wall'
    slanted_terrain:        'slanted_terrain'
    slanted_wall_gridded_temp: 'slanted_wall_gridded_temp'
    slanted_wall_gridded:   'slanted_wall_gridded'
    slanted_roof_gridded_temp: 'slanted_roof_gridded_temp'
    slanted_roof_gridded:   'slanted_roof_gridded'
    slanted_terrain_gridded_temp: 'slanted_terrain_gridded_temp'
    slanted_terrain_gridded: 'slanted_terrain_gridded'
    walls_outer:            'walls_outer'
    slanted_faces:          'slanted_faces'
    vertices:               'vertices'
    land_build:             'landcover_buildings'
    build_new:              'buildings_new'
    height_corrected:       'building_height_correct'
    height_terr_corrected:  'terrain_height_correct'
    slanted_wall_points:    'slanted_wall_points'
    trees:                  'trees'
    trees_grid:             'trees_grid'
    extras:                 'extras'
    extras_shp:             'extras_shp'
    
    
idx:
    landcover: 'lid'
    walls:     'wid'
    roofs:     'rid'
    trees:     'sid'
    buildings_depth_shp: 'gid'
    extras_shp: 'gid'
    
build_3d:
    bridge_width: 2.0
    bridge:       'bridge'
    passage:      'passage'
    overhanging:  'overhang'

origin_time: '1970-01-01 00:00:00'

# maximal distance for looking of neighbour building heights
maxbuildingdisance: 5

# slanted surfaces
do_cct: False
slanted_pars:
    max_dist: 2.0
    simplify_dist: 3.0
    min_seg: 2.0
    do_vtk: True
    clean_up: True
    empty_vert: -1
    off_dist: 4    # grid points, limit search of nearest gridpoint for slanted face
    dist2edge: 3.0
    roofs_dist2edge: 2.0
    dist2edge_filter: 0.6
    wall_build_height_max_dist: 2.0
    
cortyard_fill:
    apply: False
    count: 30
    
topo_fill_v2:
    apply: False
    count: 9
    
force_lsm_only: False
force_cyclic: False
force_cyclic_nc: 4
force_building_boundary: True
force_building_boundary_dist: 3 # distance in grid points, real distance =* dx

trees:
    lad_reduction: 1.0    # coefficient for reduction of LAD in winter
    bad_coef: 0.1         # coefficient for reduction of BAD from LAD to account branches
    nhv: 10               # number of discretization layers for calculation of tree vertical shapes
    nump: 10              # number of polygon edges for interpolation of cycles for treetops and tree trunks
    ext_coef: 0.6         # Extinction coefficient (same as in PALM code) for tree crown transmissivity
    max_lad: 1.6
    max_bad: 1.6

# compression of the output netcdf file
zlib: False
complevel: 4

# global attributes of the static driver netcdf file
# fill values
fill_values:
    b: -127
    i: -9999
    i4: -9999
    f4: -9999.0
    f8: -9999.0

ncprops:
    acronym: 'ICS'
    author: 'Jaroslav Resler, resler@cs.cas.cz'
    campaign: ''
    comment: ''
    contact_person: ''
    data_content: ''
    dependencies: ''
    institution: 'ICS Prague'
    keywords: ''
    location: ''
    palm_version: '6.0'
    references: ''
    rotation_angle: 0.0
    site: domain
    source: ''
    version: ''

# definitions of the basic constants
# needed for creation of static driver according to PID specification
ndims:
    nwater_pars: 7                 # number of elements in water_pars
    cct_max_num_vertices_per_face: 7 # number of vertices in slanted polygons
    dim_3d: 3
    cct_dim_vertex_coords: 4
    cct_dim_vertex_shifts: 1

ground:
    soil_type_default: 3   # default soil type medium-fine in terms of porosity

# definition of the landcover type ranges
type_range:
    vegetation_min: 100
    vegetation_max: 199
    pavement_min:   200
    pavement_max:   299
    water_min:      300
    water_max:      399
    building_min:   900
    building_max:   999
    bridge:         907

water_pars_temp:       # assign water body temperature according to landcover type
    1: 283.15
    2: 283.15
    3: 283.15
    4: 283.15
    5: 283.15
    6: 283.15
