# Copyright 2018-2024 Institute of Computer Science of the Czech Academy of
# Sciences, Prague, Czech Republic. Authors: Martin Bures, Jaroslav Resler.
#
# This file is part of PALM-GeM.
#
# PALM-GeM is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# PALM-GeM is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# PALM-GeM. If not, see <https://www.gnu.org/licenses/>.

domain:
    name: 'input_general'
    scenario: ''
    xl: -1e10
    xh: +1e10
    yl: -1e10
    yh: +1e10
    crop_domain: False
    fill_boundary: True
    
fishnet:
    dx: 500.0
    dy: 500.0
    
tables:
    im_landcover_or : 'imported_landcover'
    im_landcover    : 'landcover'
    streetmaps_or   : 'imported_streetmap'
    streetmaps      : 'streetmap'
    buildings_or    : 'imported_buildings'
    buildings       : 'buildings'
    dem_or          : 'imported_dem'
    dem             : 'dem'
    fishnet         : 'fishnet'

# Information about raster transformation, Info from "SELECT (ST_MetaData(rast)).* FROM inputs_schema.imported_dem LIMIT 1"
rast_tr:
    tilewidth: 32
    tileheight: 32
    scalex:  25
    scaley: -25
    skewx: 0
    skewy: 0
    
max_stl_area: 50
max_fishnet_split_area: 5000.0 # m

mt_default: 103

clean_up: False    # delete shapefiles, etc after finished run

mt:  [[11100, 203, 901],
      [11210, 203, 902],
      [11220, 203, 903],
      [11230, 203, 902],
      [11240, 203, 903],
      [11300, 203, 903],
      [12100, 203, 906],
      [12210, 201, 906],
      [12220, 202, 906],
      [12230, 209, 906],
      [12300, 203, 906],
      [12400, 103, 906],
      [13100, 101, 906],
      [13300, 101, 906],
      [13400, 108, 906],
      [14100, 118, 906],
      [14200, 103, 906],
      [21000, 102, 906],
      [22000, 101, 906],
      [23000, 103, 906],
      [24000, 102, 906],
      [25000, 102, 906],
      [31000, 117, 906],
      [32000, 110, 906],
      [33000, 112, 906],
      [40000, 110, 906],
      [50000, 301, 906],
     ]
