# Copyright 2018-2024 Institute of Computer Science of the Czech Academy of
# Sciences, Prague, Czech Republic. Authors: Martin Bures, Jaroslav Resler.
#
# This file is part of PALM-GeM.
#
# PALM-GeM is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# PALM-GeM is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# PALM-GeM. If not, see <https://www.gnu.org/licenses/>.

input_schema: 'name_of_input_schema'
pg_user: 'user_name'
pg_password: 'user_pg_password'
database: 'name_pg_database'
srid_input: 32633
srid_palm: 32633

domain:
    name: 'domain_name'
    scenario: 'scenarion_name'
    parent_domain_schema: 'name_of_parent_schema_if_exists'
    dx: 10.0   # resolution in x direction
    dy: 10.0   # resolution in y direction
    dz: 10.0   # resolution in z direction
    nx: 128    # number of gridcells in x direction
    ny: 128    # number of gridcells in y direction
    cent_x: 617146.0   # domain center, x coordinates in srid_palm
    cent_y: 5450281.0  # domain center, y coordinates in srid_palm

origin_time: '2019-07-27 00:00:00'   # origin time of simulation
