pg_user: 'user_name'
pg_password: 'user_pg_password'
database: 'name_pg_database'
srid_input: 32633
srid_palm: 32633
srid: 32632

domain:
    name: 'name_inputs_schema'
    scenario: 'name_inputs_schema_scenation'   # >> schema name: name + _ + scenarion
    xl: 612999                                 # lower left corner, x coordinates in srid, in case of domain cropping
    xh: 621437                                 # top  right corner, x coordinates in srid, in case of domain cropping
    yl: 5446031                                # lower left corner, y coordinates in srid, in case of domain cropping
    yh: 5454982                                # top  right corner, y coordinates in srid, in case of domain cropping
    crop_domain: True                          # Crop domain by rectangular polygon defined by [xl, yl, xh, yh]
    fill_boundary: False                       # In case of missing polygon, fill with mt_default (see default_config_preproc.yaml)