# Copyright 2018-2024 Institute of Computer Science of the Czech Academy of
# Sciences, Prague, Czech Republic. Authors: Martin Bures, Jaroslav Resler.
#
# This file is part of PALM-GeM.
#
# PALM-GeM is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# PALM-GeM is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# PALM-GeM. If not, see <https://www.gnu.org/licenses/>.

pg_user: 'your_pg_user'
pg_password: 'your_pg_password'
database: 'palm_static'

scratch: False
create_grid: True # TODO: create this switches to only calculate what user wants {navaznost}
#palm_debug = False

input_schema: 'inputs_prague'
gisinputs: 'DEJV3'

domain:
    name: 'legerova_02_martin'
    scenario:   'validation_summer'
    parent_domain_schema: ''
    dx: 2.0
    dy: 2.0
    dz: 0.0
    nx: 100
    ny: 100
    cent_x: 459180
    cent_y: 5547800
